import drillDecks from '../data/drill-decks.json' with { type: 'json' };
import type { DrillLeague } from './move-counts';

// Generated by scripts/sync-drill-decks.js from the same rankings the app ships.
// Isolated in its own module so only the /move-counts island pulls the JSON in.
export const drillLeagues = (drillDecks as { leagues: Record<string, DrillLeague> }).leagues;

/**
 * Deck order on the page — Great League first, as the GL-dominant audience
 * expects. Little League is not offered: it is a rotating GBL format whose
 * roster is pre-evolutions, not the Pokémon you spend a season counting against.
 */
export const DRILL_LEAGUE_IDS = ['great', 'ultra', 'master'] as const;

export type DrillLeagueId = (typeof DRILL_LEAGUE_IDS)[number];

/**
 * Localized league names, shared by the drill's league buttons and the chart's
 * accordion headings so the two can never disagree about what a league is called.
 */
export const LEAGUE_LABEL_KEYS = {
  great: 'iv.great_league',
  ultra: 'iv.ultra_league',
  master: 'iv.master_league',
} as const satisfies Record<DrillLeagueId, string>;
