import drillDecks from '../data/drill-decks.json' with { type: 'json' };
// Type-only, so Node's type stripping erases it: this module is imported by
// scripts/validate-data.js and the test runner, neither of which resolves the
// extensionless specifiers Vite allows.
import type { ui, defaultLang } from '../i18n/ui';
import { cupBadgeSrc } from './cup-badges.ts';
import type { GblLeagueTier } from './gbl-schedule';
import type { DrillLeague } from './move-counts';

// Generated by scripts/sync-drill-decks.js from the same rankings the app ships.
// Isolated in its own module so only the /move-counts island pulls the JSON in.
export const drillLeagues = (drillDecks as { leagues: Record<string, DrillLeague> }).leagues;

type UiKey = keyof (typeof ui)[typeof defaultLang];

/**
 * The drill quizzes the three core leagues, Great League first as the
 * GL-dominant audience expects; its button row is a hardcoded 3-column grid.
 * The limited cups and Little are reference-only — see CHART_FORMATS.
 */
export const DRILL_LEAGUE_IDS = ['great', 'ultra', 'master'] as const;

/**
 * Every format the chart lists, as `cupName`/`tier` pairs so the badge and the
 * name resolve through the same helpers the GBL calendar uses — one cup cannot
 * wear two icons or carry two names across the two pages.
 *
 * The chart is the page's indexable body, so it covers the whole season's
 * rotation, not just the three the drill quizzes. Both read the same decks, so
 * the reference and the quiz still cannot disagree about a count.
 *
 * Absent from this season's rotation, each for a reason that is not policy but
 * data: the Fantasy Cup's ranking is four months stale, and the Mega Color,
 * Mega Halloween and Mega Catch cups have no ranking file at all (they are
 * their own cups in the app, not the plain cup with a flag, so the base cup's
 * ranking is not a stand-in). Add them the moment a current ranking lands.
 */
export const CHART_FORMATS = [
  { id: 'great', cupName: 'all', tier: 'great' },
  { id: 'ultra', cupName: 'all', tier: 'ultra' },
  { id: 'master', cupName: 'all', tier: 'master' },
  { id: 'little', cupName: 'all', tier: 'little' },
  { id: 'megaGreat', cupName: 'mega', tier: 'great' },
  { id: 'megaUltra', cupName: 'mega', tier: 'ultra' },
  { id: 'megaMaster', cupName: 'mega', tier: 'master' },
  { id: 'willpower', cupName: 'willpower', tier: 'great' },
  { id: 'retro', cupName: 'retro', tier: 'great' },
  { id: 'laic2026', cupName: 'laic2026', tier: 'great' },
] as const satisfies readonly { id: string; cupName: string; tier: GblLeagueTier }[];

export const CHART_LEAGUE_IDS = CHART_FORMATS.map((f) => f.id);

export type DrillLeagueId = (typeof DRILL_LEAGUE_IDS)[number];
export type ChartLeagueId = (typeof CHART_FORMATS)[number]['id'];

/**
 * Localized league names, shared by the drill's league buttons and the chart's
 * accordion headings so the two can never disagree about what a league is called.
 */
export const LEAGUE_LABEL_KEYS = {
  great: 'iv.great_league',
  ultra: 'iv.ultra_league',
  master: 'iv.master_league',
  little: 'iv.little_league',
} as const satisfies Record<string, UiKey>;

const FORMAT_BY_ID = new Map(CHART_FORMATS.map((f) => [f.id as ChartLeagueId, f]));

/**
 * The chart heading for a format.
 *
 * A Mega Edition is composed rather than stored: `iv.*_league` and
 * `gbl.rule_mega` are already translated in all ten locales, so "Lega Super:
 * Edizione Mega" falls out for free. A dedicated `drill.mega_*` string was
 * English-only and left nine locales reading English mid-page.
 */
export function chartLabel(t: (key: UiKey) => string, id: ChartLeagueId): string {
  const format = FORMAT_BY_ID.get(id)!;
  const league = t(LEAGUE_LABEL_KEYS[format.tier]);

  if (format.cupName === 'mega') return `${league}: ${t('gbl.rule_mega')}`;
  if (format.cupName === 'all') return league;
  return t(`gbl.name_${format.cupName}` as UiKey);
}

/** Badge art per chart format, resolved the same way the GBL calendar does. */
export const LEAGUE_BADGES = Object.fromEntries(
  CHART_FORMATS.map((f) => [f.id, cupBadgeSrc(f.cupName, f.tier)]),
) as Record<ChartLeagueId, string>;
