import pools from '../data/move-pools.json' with { type: 'json' };

// Generated by scripts/sync-move-pools.js. Every released species and the moves
// it can learn, trimmed to the four fields a move count needs. Isolated in its
// own module so only the /move-counts lookup pulls the JSON in.

/** A move, reduced to what a count depends on. `energyGain` is energy per *use*. */
export interface PoolMove {
  name: string;
  type: string;
  energy: number;
  energyGain: number;
}

export interface PoolSpecies {
  id: string;
  dex: number;
  name: string;
  /** Move ids with `energyGain > 0`. */
  fast: string[];
  /** Move ids with `energy > 0`. */
  charged: string[];
}

const data = pools as { moves: Record<string, PoolMove>; species: PoolSpecies[] };

export const poolMoves = data.moves;
export const poolSpecies = data.species;
