android: "https://play.google.com/store/apps/details?id=com.baru.software.oak"
iOS: "https://apps.apple.com/us/app/battleflow/id6738843812"
video: "video.mov"
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
  - 5.png
  - 6.png
